### ISSUE TITLE
Excessive Notifications when the Boscloner has Disconnected

### ISSUE THREAD

**Issue by Boscloner** [Boscloner/Boscloner-Android-v2#24]
Once the Boscloner is disconnected from the app, the user receives a notification to alert them that the Boscloner is no longer connected.

However, every few seconds, the user receives a new alert/notification that the Boscloner is disconnected. This is not an ideal experience. 

The Boscloner app seems to attempt reconnection every few seconds (This is good!), but the notification should only arrive once when the connection is lost. This notification should not be repeated on every reconnect attempt.

**Comment by aleksamarkoni** [comment]
This should be fixed now.

**Comment by aleksamarkoni** [comment]
But please maybe there will be other cases when this might happen, like when scanning.

**Comment by Boscloner** [comment]
This issue persists.

After disconnecting the Boscloner board from power - the phone receives a notification that the Boscloner is disconnected. However, while the Boscloner is disconnected, every 9 seconds or so, the phone alerts the user again that the Boscloner is disconnected.

**Comment by aleksamarkoni** [comment]
Ok I guess that I did something wrong, there is like 9 sec or so cycle, that does the scanning, and trying to connect with the device. It's strange that you get that second notification since you should also get others, I will recheck it again.

**Comment by aleksamarkoni** [comment]
This is fixed now. The flow was good, but after every bluetooth scan for the boscloner I was updating the notification as well, and since the notification is same ("connection lost") there is no need to update it. This should work now.

**Comment by Boscloner** [comment]
Excellent. The Bluetooth reconnection and the disconnect notification work as expected now.
